<!DOCTYPE html>
<html lang="fr">

<head>
	<meta charset="utf-8">
	<meta name="description" content="description de la page" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
	<title>starter project</title>
	<link rel="stylesheet" href="public/utilities/CSS_utilities.css" media="all" />
	<link rel="stylesheet" href="public/css/style.css" media="screen" />
	<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
	<script src="public/utilities/utilities.js"></script>
</head>

<body>
	<!--HEADER-->
	<header>
		<h1>Starter Project</h1>
		<nav>
		</nav>
	</header>
	<!--MAIN CONTENT-->
	<main>
	</main>
	<!--FOOTER-->
	<footer>
		<small>
		</small>
	</footer>
	<script src="public/js/main.js"></script>
</body>

</html>